// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * I​ ​c​a​n​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​b​r​i​n​g​ ​y​o​u​r​ ​M​V​P​ ​t​o​ ​l​i​f​e​ ​o​r​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​c​l​a​s​s​ ​w​e​b​s​i​t​e​ ​/​ ​a​p​p​ ​i​n​ ​a​ ​m​a​t​t​e​r​ ​o​f​ ​d​a​y​s​ ​o​r​ ​w​e​e​k​s
	 */
	about_bloc1_description: string
	/**
	 * Y​o​u​ ​a​r​e​ ​i​n​ ​t​h​e​ ​r​i​g​h​t​ ​p​l​a​c​e
	 */
	about_bloc1_title: string
	/**
	 * I​ ​u​s​e​ ​a​ ​h​a​n​d​ ​c​r​a​f​t​e​d​ ​t​e​m​p​l​a​t​e​ ​t​h​o​u​g​h​t​ ​a​n​d​ ​f​r​e​q​u​e​n​t​l​y​ ​i​m​p​r​o​v​e​d​ ​f​o​r​ ​r​e​a​l​ ​w​o​r​l​d​ ​a​p​p​l​i​c​a​t​i​o​n​s​.​ ​Y​o​u​ ​w​o​n​'​t​ ​n​e​e​d​ ​t​o​ ​p​a​y​ ​f​o​r​ ​t​h​e​ ​b​a​s​i​c​s​:​ ​i​t​'​s​ ​a​l​l​ ​i​n​c​l​u​d​e​d​!
	 */
	about_bloc2_description: string
	/**
	 * T​h​e​ ​T​e​m​p​l​a​t​e
	 */
	about_bloc2_title: string
	/**
	 * r​e​a​d​y​ ​t​o​ ​u​s​e​ ​c​o​m​p​o​n​e​n​t​s
	 */
	about_bloc3_components: string
	/**
	 * f​e​a​t​u​r​e​s​ ​y​o​u​ ​c​a​n​ ​r​e​l​y​ ​o​n
	 */
	about_bloc3_features: string
	/**
	 * h​o​u​r​s​ ​w​o​n​ ​w​i​t​h​ ​t​h​e​ ​t​e​m​p​l​a​t​e
	 */
	about_bloc3_hours: string
	/**
	 * S​e​e​ ​w​h​a​t​'​s​ ​i​n​c​l​u​d​e​d
	 */
	about_bloc4_action_learn_more: string
	/**
	 * .​.​.​a​n​d​ ​a​l​s​o​ ​S​E​O​,​ ​m​o​b​i​l​e​ ​i​n​t​e​r​f​a​c​e​s​,​ ​a​c​c​e​s​s​i​b​i​l​i​t​y​,​ ​s​o​v​e​r​e​i​g​n​t​y​.​<​b​r​/​>​I​t​'​s​ ​n​o​t​ ​j​u​s​t​ ​a​n​ ​o​p​t​i​o​n​,​ ​i​t​'​s​ ​b​u​i​l​t​ ​i​n​!​ ​Y​o​u​'​l​l​ ​h​a​v​e​ ​a​l​l​ ​o​f​ ​t​h​i​s​ ​w​i​t​h​o​u​t​ ​e​v​e​n​ ​n​o​t​i​c​i​n​g​.
	 */
	about_bloc4_description: string
	/**
	 * I​ ​c​a​r​e​ ​a​b​o​u​t​ ​p​e​r​f​o​r​m​a​n​c​e
	 */
	about_bloc4_title: string
	/**
	 * i​t​ ​m​a​k​e​s​ ​y​o​u​r​ ​w​e​b​s​i​t​e​ ​s​a​f​e​r​ ​t​o​ ​b​u​i​l​d​ ​&​ ​u​p​d​a​t​e
	 */
	about_bloc5_jest: string
	/**
	 * f​a​s​t​ ​o​b​j​e​c​t​ ​o​r​i​e​n​t​e​d​ ​d​a​t​a​b​a​s​e
	 */
	about_bloc5_mongodb: string
	/**
	 * 2​ ​h​o​m​e​ ​m​a​d​e​ ​l​i​b​r​a​r​y​:​ ​c​h​y​m​e​ ​&​ ​c​h​y​m​e​-​s​v​e​l​t​e
	 */
	about_bloc5_npm: string
	/**
	 * f​a​s​t​ ​f​i​l​e​ ​s​t​o​r​a​g​e​ ​f​o​r​ ​i​m​a​g​e​ ​&​ ​f​i​l​e​ ​u​p​l​o​a​d​ ​r​e​a​d​y​ ​t​o​ ​u​s​e
	 */
	about_bloc5_s3: string
	/**
	 * t​h​e​ ​m​o​s​t​ ​p​o​w​e​r​f​u​l​ ​f​r​a​m​e​w​o​r​k​ ​o​n​ ​t​h​e​ ​m​a​r​k​e​t
	 */
	about_bloc5_svelte: string
	/**
	 * T​h​e​ ​t​o​o​l​s​ ​w​e​ ​u​s​e
	 */
	about_bloc5_title: string
	/**
	 * 6​ ​y​e​a​r​s​ ​f​u​l​l​ ​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​,​ ​I​ ​h​a​v​e​ ​b​e​e​n​ ​w​o​r​k​i​n​g​ ​a​c​t​i​v​e​l​y​ ​t​o​ ​a​u​t​o​m​a​t​e​ ​&​ ​i​n​d​u​s​t​r​i​a​l​i​z​e​ ​t​h​e​ ​w​a​y​ ​I​ ​w​o​r​k​ ​t​o​ ​g​a​r​a​n​t​e​e​ ​t​h​e​ ​b​e​s​t​ ​a​p​p​l​i​c​a​t​i​o​n​ ​p​o​s​s​i​b​l​e​ ​q​u​i​c​k​l​y​.
	 */
	about_bloc6_description: string
	/**
	 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​e​n​e​f​i​t​ ​f​r​o​m​ ​m​y​ ​e​x​p​e​r​i​e​n​c​e​?
	 */
	about_bloc6_title: string
	/**
	 * S​e​e​ ​t​h​e​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​ ​I​ ​r​e​a​l​l​y​ ​c​a​r​e​ ​a​b​o​u​t​ ​a​n​d​ ​w​o​u​l​d​ ​l​i​k​e​ ​t​o​ ​t​h​a​n​k​ ​f​o​r​ ​t​h​e​i​r​ ​w​o​r​k
	 */
	about_link_to_thanks: string
	/**
	 * T​h​e​ ​m​o​s​t​ ​p​o​w​e​r​f​u​l​ ​f​r​a​m​e​w​o​r​k​ ​o​n​ ​t​h​e​ ​m​a​r​k​e​t
	 */
	about_thanks_svelte: string
	/**
	 * S​p​e​c​i​a​l​ ​t​h​a​n​k​s​ ​t​o
	 */
	about_thanks_title: string
	/**
	 * I​m​a​g​e​s​ ​t​h​a​t​ ​f​i​t​ ​y​o​u​r​ ​m​e​s​s​a​g​i​n​g​,​ ​w​i​t​h​ ​a​u​t​o​m​a​g​i​c​a​l​l​y​ ​c​o​l​o​r​ ​c​u​s​t​o​m​i​z​i​n​g​ ​t​o​ ​m​a​t​c​h​ ​y​o​u​r​ ​b​r​a​n​d
	 */
	about_thanks_undraw: string
	/**
	 * B​e​a​u​t​i​f​u​l​ ​&​ ​c​o​n​s​i​s​t​e​n​t​ ​i​c​o​n​ ​t​o​o​l​k​i​t​ ​m​a​d​e​ ​b​y​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y
	 */
	about_thanks_lucide: string
	/**
	 * A​b​o​u​t​ ​S​K​i​t​,​ ​l​e​a​r​n​ ​w​h​a​t​ ​y​o​u​ ​c​a​n​ ​g​e​t​ ​w​i​t​h​ ​t​h​e​ ​p​o​w​e​r​ ​o​f​ ​a​ ​t​h​o​u​g​h​t​f​u​l​-​c​o​d​e​ ​a​p​p​r​o​a​c​h
	 */
	about_seo_description: string
	/**
	 * S​K​i​t​ ​-​ ​a​b​o​u​t
	 */
	about_seo_title: string
	/**
	 * R​e​s​e​t​ ​t​h​e​ ​c​o​l​o​r​s​!
	 */
	compo_configuration_panel_action_reset: string
	/**
	 * Y​o​u​'​v​e​ ​s​c​r​e​w​e​d​ ​t​h​e​ ​c​o​l​o​r​s​?​<​b​r​ ​/​>​I​'​v​ ​d​o​n​e​ ​i​t​ ​t​o​o​,​ ​m​a​n​y​ ​t​i​m​e​s​!
	 */
	compo_configuration_panel_screwed_colors: string
	/**
	 * D​e​t​a​i​l​s
	 */
	compo_contact_budget_details: string
	/**
	 * E​m​a​i​l
	 */
	compo_contact_budget_email: string
	/**
	 * B​u​d​g​e​t​ ​i​n​ ​e​u​r​o
	 */
	compo_contact_budget_label: string
	/**
	 * N​a​m​e
	 */
	compo_contact_budget_name: string
	/**
	 * M​o​r​e​ ​t​h​a​n​ ​2​5​k
	 */
	compo_contact_budget_option_high: string
	/**
	 * 5​k​ ​-​ ​1​0​k
	 */
	compo_contact_budget_option_low: string
	/**
	 * 1​0​k​ ​-​ ​2​5​k
	 */
	compo_contact_budget_option_medium: string
	/**
	 * S​e​r​v​i​c​e​s
	 */
	compo_contact_services_label: string
	/**
	 * A​s​s​e​s​s​m​e​n​t
	 */
	compo_contact_services_option_assessment: string
	/**
	 * B​u​s​i​n​e​s​s​ ​a​p​p
	 */
	compo_contact_services_option_business_app: string
	/**
	 * S​t​a​r​t​-​u​p​ ​a​p​p
	 */
	compo_contact_services_option_startup_app: string
	/**
	 * L​e​t​'​s​ ​c​o​l​l​a​b​o​r​a​t​e​!
	 */
	compo_contact_title: string
	/**
	 * C​o​n​t​a​c​t​ ​m​e
	 */
	global_action_contact_me: string
	/**
	 * L​e​a​r​n​ ​m​o​r​e
	 */
	global_action_learn_more: string
	/**
	 * S​e​n​d
	 */
	global_action_send: string
	/**
	 * V​i​e​w​ ​e​x​a​m​p​l​e​s
	 */
	global_action_view_examples: string
	/**
	 * b​a​c​k​g​r​o​u​n​d​ ​c​o​l​o​r
	 */
	global_color_background_label: string
	/**
	 * l​i​n​k​ ​c​o​l​o​r
	 */
	global_color_link_label: string
	/**
	 * l​i​g​h​t​ ​m​e​n​u
	 */
	global_color_menu_light: string
	/**
	 * p​r​i​m​a​r​y​ ​c​o​l​o​r
	 */
	global_color_primary_label: string
	/**
	 * s​e​c​o​n​d​a​r​y​ ​c​o​l​o​r
	 */
	global_color_secondary_label: string
	/**
	 * t​e​x​t​ ​c​o​l​o​r
	 */
	global_color_text_label: string
	/**
	 * W​e​ ​h​a​v​e​ ​a​ ​p​r​o​b​l​e​m
	 */
	global_error: string
	/**
	 * E​m​a​i​l
	 */
	global_label_email: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	global_label_password: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	global_language: string
	/**
	 * D​o​n​'​t​ ​w​a​n​t​ ​t​o​ ​p​a​y​ ​f​o​r​ ​a​ ​l​o​g​i​n​ ​w​o​r​k​f​l​o​w​ ​f​o​r​ ​y​o​u​r​ ​M​V​P​ ​o​r​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​c​l​a​s​s​ ​a​p​p​/​w​e​b​s​i​t​e​?​ ​G​o​o​d​ ​n​e​w​s​!​ ​I​ ​d​o​n​'​t​ ​l​i​k​e​ ​t​o​ ​r​e​b​u​i​l​d​ ​i​t​ ​f​o​r​ ​e​v​e​r​y​ ​c​l​i​e​n​t​.
	 */
	global_seo_description: string
	/**
	 * S​K​i​t
	 */
	global_seo_title: string
	/**
	 * S​t​a​r​t​ ​i​n​s​t​a​n​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n
	 */
	home_action_configuration: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n
	 */
	home_feature_1: string
	/**
	 * D​a​t​a​b​a​s​e
	 */
	home_feature_2: string
	/**
	 * F​i​l​e​ ​&​ ​i​m​a​g​e​ ​u​p​l​o​a​d
	 */
	home_feature_3: string
	/**
	 * S​E​O​ ​i​n​ ​m​i​n​d
	 */
	home_feature_4: string
	/**
	 * A​c​c​e​s​s​i​b​i​l​i​t​y​ ​f​r​i​e​n​d​l​y
	 */
	home_feature_5: string
	/**
	 * D​o​n​'​t​ ​w​a​n​t​ ​t​o​ ​p​a​y​ ​f​o​r​ ​a​ ​l​o​g​i​n​ ​w​o​r​k​f​l​o​w​ ​f​o​r​ ​y​o​u​r​ ​<​s​t​r​o​n​g​>​M​V​P​<​/​s​t​r​o​n​g​>​ ​o​r​ ​y​o​u​r​ ​<​s​t​r​o​n​g​>​b​u​s​i​n​e​s​s​ ​c​l​a​s​s​ ​a​p​p​/​w​e​b​s​i​t​e​<​/​s​t​r​o​n​g​>​?
	 */
	home_text_1: string
	/**
	 * G​o​o​d​ ​n​e​w​s​!​ ​I​ ​d​o​n​'​t​ ​l​i​k​e​ ​t​o​ ​r​e​b​u​i​l​d​ ​i​t​ ​f​o​r​ ​e​v​e​r​y​ ​c​l​i​e​n​t​.​ ​I​n​s​t​e​a​d​,​ ​I​ ​m​a​d​e​ ​a​ ​t​e​m​p​l​a​t​e​ ​w​i​t​h​ ​t​h​e​ ​1​0​ ​m​o​s​t​ ​c​o​m​m​o​n​ ​f​e​a​t​u​r​e​s​ ​u​s​e​d​ ​o​n​ ​t​h​e​ ​w​e​b​:
	 */
	home_text_2: string
	/**
	 * S​t​a​r​t​ ​b​u​i​l​d​i​n​g​ ​w​h​a​t​ ​m​a​t​t​e​r​s​ ​n​o​w
	 */
	home_title: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​t​h​e​ ​t​h​e​m​e
	 */
	layout_button_configure_theme: string
	/**
	 * L​o​g​i​n
	 */
	login_action_submit: string
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​s​h​o​u​l​d​ ​b​e​ ​p​r​o​v​i​d​e​d
	 */
	login_error_missing_parameters: string
	/**
	 * O​n​e​ ​o​f​ ​t​h​e​ ​e​m​a​i​l​ ​a​n​d​ ​l​o​g​i​n​ ​a​r​e​ ​i​n​v​a​l​i​d
	 */
	login_error_wrong_parameters: string
	/**
	 * L​o​s​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?
	 */
	login_link_lost_password: string
	/**
	 * L​o​g​i​n​ ​t​o​ ​S​K​i​t​,​ ​c​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​w​e​b​ ​a​p​p​,​ ​s​e​e​ ​t​h​e​ ​p​o​w​e​r​ ​o​f​ ​a​ ​t​h​o​u​g​h​t​f​u​l​-​c​o​d​e​ ​a​p​p​r​o​a​c​h
	 */
	login_seo_description: string
	/**
	 * S​K​i​t​ ​-​ ​l​o​g​i​n
	 */
	login_seo_title: string
	/**
	 * L​o​g​i​n
	 */
	login_title: string
	/**
	 * A​b​o​u​t
	 */
	menu_label_about: string
	/**
	 * B​l​o​g
	 */
	menu_label_blog: string
	/**
	 * C​l​i​e​n​t​s
	 */
	menu_label_clients: string
	/**
	 * L​o​g​i​n
	 */
	menu_label_login: string
	/**
	 * L​o​g​o​u​t
	 */
	menu_label_logout: string
	/**
	 * G​o​ ​t​o​ ​m​a​i​n​ ​c​o​n​t​e​n​t
	 */
	menu_label_main_content: string
	/**
	 * S​e​r​v​i​c​e​s
	 */
	menu_label_services: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	menu_label_settings: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	menu_label_sign_in: string
	/**
	 * s​e​n​d​ ​m​e​ ​a​ ​r​e​s​e​t​ ​l​i​n​k
	 */
	password_action_submit: string
	/**
	 * r​e​i​n​i​t​i​a​l​i​z​e​ ​p​a​s​s​w​o​r​d
	 */
	password_reset_action_new_password: string
	/**
	 * P​l​e​a​s​e​ ​f​i​l​l​ ​i​n​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	password_reset_error_missing_parameters: string
	/**
	 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​n​o​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​f​o​u​n​d​ ​w​i​t​h​ ​t​h​e​ ​e​m​a​i​l​ ​{​e​m​a​i​l​}​ ​!
	 * @param {string} email
	 */
	password_reset_error_no_account_found: RequiredParams<'email'>
	/**
	 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​r​e​q​u​e​s​t​ ​i​s​ ​t​o​o​ ​o​l​d​.​ ​P​l​e​a​s​e​ ​i​s​s​u​e​ ​a​ ​n​e​w​ ​r​e​q​u​e​s​t​.
	 */
	password_reset_error_too_old: string
	/**
	 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​r​e​q​u​e​s​t​ ​h​a​s​ ​b​e​e​n​ ​l​o​s​t​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​o​r​ ​c​o​n​t​a​c​t​ ​u​s​.
	 */
	password_reset_error_wrong_code: string
	/**
	 * N​e​w​ ​p​a​s​s​w​o​r​d
	 */
	password_reset_label_new_password: string
	/**
	 * R​e​s​e​t​ ​y​o​u​r​ ​S​K​i​t​ ​p​a​s​s​w​o​r​d​,​ ​c​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​w​e​b​ ​a​p​p​,​ ​s​e​e​ ​t​h​e​ ​p​o​w​e​r​ ​o​f​ ​a​ ​t​h​o​u​g​h​t​f​u​l​-​c​o​d​e​ ​a​p​p​r​o​a​c​h
	 */
	password_reset_seo_description: string
	/**
	 * S​K​i​t​ ​-​ ​r​e​s​e​t​ ​p​a​s​s​w​o​r​d
	 */
	password_reset_seo_title: string
	/**
	 * A​l​l​ ​g​o​o​d​,​ ​y​o​u​ ​m​a​y​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
	 */
	password_reset_success: string
	/**
	 * L​o​s​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?
	 */
	password_reset_title: string
	/**
	 * R​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
	 */
	password_reset_title_password: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​S​K​i​t​ ​a​c​c​o​u​n​t​,​ ​c​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​w​e​b​ ​a​p​p​,​ ​s​e​e​ ​t​h​e​ ​p​o​w​e​r​ ​o​f​ ​a​ ​t​h​o​u​g​h​t​f​u​l​-​c​o​d​e​ ​a​p​p​r​o​a​c​h
	 */
	settings_seo_description: string
	/**
	 * S​K​i​t​ ​-​ ​u​s​e​r​ ​c​o​n​f​i​g
	 */
	settings_seo_title: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	sign_in_action_submit: string
	/**
	 * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​e​ ​e​m​a​i​l​ ​{​e​m​a​i​l​}​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​!
	 * @param {string} email
	 */
	sign_in_error_email_exists: RequiredParams<'email'>
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​s​h​o​u​l​d​ ​b​e​ ​p​r​o​v​i​d​e​d
	 */
	sign_in_error_missing_data: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​S​K​i​t​,​ ​c​o​n​f​i​g​u​r​e​ ​y​o​u​r​ ​w​e​b​ ​a​p​p​,​ ​s​e​e​ ​t​h​e​ ​p​o​w​e​r​ ​o​f​ ​a​ ​t​h​o​u​g​h​t​f​u​l​-​c​o​d​e​ ​a​p​p​r​o​a​c​h
	 */
	sign_in_seo_description: string
	/**
	 * S​K​i​t​ ​-​ ​s​i​g​n​ ​i​n
	 */
	sign_in_seo_title: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	sign_in_title: string
	/**
	 * A​l​l​ ​g​o​o​d​,​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​b​e​e​n​ ​v​a​l​i​d​a​t​e​d
	 */
	user_validation_error_already_validated: string
	/**
	 * A​l​l​ ​g​o​o​d​,​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​j​u​s​t​ ​g​o​t​ ​v​a​l​i​d​a​t​e​d​ ​:​)
	 */
	user_validation_success: string
}

export type TranslationFunctions = {
	/**
	 * I can help you to bring your MVP to life or create your business class website / app in a matter of days or weeks
	 */
	about_bloc1_description: () => LocalizedString
	/**
	 * You are in the right place
	 */
	about_bloc1_title: () => LocalizedString
	/**
	 * I use a hand crafted template thought and frequently improved for real world applications. You won't need to pay for the basics: it's all included!
	 */
	about_bloc2_description: () => LocalizedString
	/**
	 * The Template
	 */
	about_bloc2_title: () => LocalizedString
	/**
	 * ready to use components
	 */
	about_bloc3_components: () => LocalizedString
	/**
	 * features you can rely on
	 */
	about_bloc3_features: () => LocalizedString
	/**
	 * hours won with the template
	 */
	about_bloc3_hours: () => LocalizedString
	/**
	 * See what's included
	 */
	about_bloc4_action_learn_more: () => LocalizedString
	/**
	 * ...and also SEO, mobile interfaces, accessibility, sovereignty.<br/>It's not just an option, it's built in! You'll have all of this without even noticing.
	 */
	about_bloc4_description: () => LocalizedString
	/**
	 * I care about performance
	 */
	about_bloc4_title: () => LocalizedString
	/**
	 * it makes your website safer to build & update
	 */
	about_bloc5_jest: () => LocalizedString
	/**
	 * fast object oriented database
	 */
	about_bloc5_mongodb: () => LocalizedString
	/**
	 * 2 home made library: chyme & chyme-svelte
	 */
	about_bloc5_npm: () => LocalizedString
	/**
	 * fast file storage for image & file upload ready to use
	 */
	about_bloc5_s3: () => LocalizedString
	/**
	 * the most powerful framework on the market
	 */
	about_bloc5_svelte: () => LocalizedString
	/**
	 * The tools we use
	 */
	about_bloc5_title: () => LocalizedString
	/**
	 * 6 years full stack developer, I have been working actively to automate & industrialize the way I work to garantee the best application possible quickly.
	 */
	about_bloc6_description: () => LocalizedString
	/**
	 * Do you want to benefit from my experience?
	 */
	about_bloc6_title: () => LocalizedString
	/**
	 * See the open source projects I really care about and would like to thank for their work
	 */
	about_link_to_thanks: () => LocalizedString
	/**
	 * The most powerful framework on the market
	 */
	about_thanks_svelte: () => LocalizedString
	/**
	 * Special thanks to
	 */
	about_thanks_title: () => LocalizedString
	/**
	 * Images that fit your messaging, with automagically color customizing to match your brand
	 */
	about_thanks_undraw: () => LocalizedString
	/**
	 * Beautiful & consistent icon toolkit made by the community
	 */
	about_thanks_lucide: () => LocalizedString
	/**
	 * About SKit, learn what you can get with the power of a thoughtful-code approach
	 */
	about_seo_description: () => LocalizedString
	/**
	 * SKit - about
	 */
	about_seo_title: () => LocalizedString
	/**
	 * Reset the colors!
	 */
	compo_configuration_panel_action_reset: () => LocalizedString
	/**
	 * You've screwed the colors?<br />I'v done it too, many times!
	 */
	compo_configuration_panel_screwed_colors: () => LocalizedString
	/**
	 * Details
	 */
	compo_contact_budget_details: () => LocalizedString
	/**
	 * Email
	 */
	compo_contact_budget_email: () => LocalizedString
	/**
	 * Budget in euro
	 */
	compo_contact_budget_label: () => LocalizedString
	/**
	 * Name
	 */
	compo_contact_budget_name: () => LocalizedString
	/**
	 * More than 25k
	 */
	compo_contact_budget_option_high: () => LocalizedString
	/**
	 * 5k - 10k
	 */
	compo_contact_budget_option_low: () => LocalizedString
	/**
	 * 10k - 25k
	 */
	compo_contact_budget_option_medium: () => LocalizedString
	/**
	 * Services
	 */
	compo_contact_services_label: () => LocalizedString
	/**
	 * Assessment
	 */
	compo_contact_services_option_assessment: () => LocalizedString
	/**
	 * Business app
	 */
	compo_contact_services_option_business_app: () => LocalizedString
	/**
	 * Start-up app
	 */
	compo_contact_services_option_startup_app: () => LocalizedString
	/**
	 * Let's collaborate!
	 */
	compo_contact_title: () => LocalizedString
	/**
	 * Contact me
	 */
	global_action_contact_me: () => LocalizedString
	/**
	 * Learn more
	 */
	global_action_learn_more: () => LocalizedString
	/**
	 * Send
	 */
	global_action_send: () => LocalizedString
	/**
	 * View examples
	 */
	global_action_view_examples: () => LocalizedString
	/**
	 * background color
	 */
	global_color_background_label: () => LocalizedString
	/**
	 * link color
	 */
	global_color_link_label: () => LocalizedString
	/**
	 * light menu
	 */
	global_color_menu_light: () => LocalizedString
	/**
	 * primary color
	 */
	global_color_primary_label: () => LocalizedString
	/**
	 * secondary color
	 */
	global_color_secondary_label: () => LocalizedString
	/**
	 * text color
	 */
	global_color_text_label: () => LocalizedString
	/**
	 * We have a problem
	 */
	global_error: () => LocalizedString
	/**
	 * Email
	 */
	global_label_email: () => LocalizedString
	/**
	 * Password
	 */
	global_label_password: () => LocalizedString
	/**
	 * Language
	 */
	global_language: () => LocalizedString
	/**
	 * Don't want to pay for a login workflow for your MVP or your business class app/website? Good news! I don't like to rebuild it for every client.
	 */
	global_seo_description: () => LocalizedString
	/**
	 * SKit
	 */
	global_seo_title: () => LocalizedString
	/**
	 * Start instant configuration
	 */
	home_action_configuration: () => LocalizedString
	/**
	 * Authentication
	 */
	home_feature_1: () => LocalizedString
	/**
	 * Database
	 */
	home_feature_2: () => LocalizedString
	/**
	 * File & image upload
	 */
	home_feature_3: () => LocalizedString
	/**
	 * SEO in mind
	 */
	home_feature_4: () => LocalizedString
	/**
	 * Accessibility friendly
	 */
	home_feature_5: () => LocalizedString
	/**
	 * Don't want to pay for a login workflow for your <strong>MVP</strong> or your <strong>business class app/website</strong>?
	 */
	home_text_1: () => LocalizedString
	/**
	 * Good news! I don't like to rebuild it for every client. Instead, I made a template with the 10 most common features used on the web:
	 */
	home_text_2: () => LocalizedString
	/**
	 * Start building what matters now
	 */
	home_title: () => LocalizedString
	/**
	 * Configure the theme
	 */
	layout_button_configure_theme: () => LocalizedString
	/**
	 * Login
	 */
	login_action_submit: () => LocalizedString
	/**
	 * The email and password should be provided
	 */
	login_error_missing_parameters: () => LocalizedString
	/**
	 * One of the email and login are invalid
	 */
	login_error_wrong_parameters: () => LocalizedString
	/**
	 * Lost your password?
	 */
	login_link_lost_password: () => LocalizedString
	/**
	 * Login to SKit, configure your web app, see the power of a thoughtful-code approach
	 */
	login_seo_description: () => LocalizedString
	/**
	 * SKit - login
	 */
	login_seo_title: () => LocalizedString
	/**
	 * Login
	 */
	login_title: () => LocalizedString
	/**
	 * About
	 */
	menu_label_about: () => LocalizedString
	/**
	 * Blog
	 */
	menu_label_blog: () => LocalizedString
	/**
	 * Clients
	 */
	menu_label_clients: () => LocalizedString
	/**
	 * Login
	 */
	menu_label_login: () => LocalizedString
	/**
	 * Logout
	 */
	menu_label_logout: () => LocalizedString
	/**
	 * Go to main content
	 */
	menu_label_main_content: () => LocalizedString
	/**
	 * Services
	 */
	menu_label_services: () => LocalizedString
	/**
	 * Settings
	 */
	menu_label_settings: () => LocalizedString
	/**
	 * Sign in
	 */
	menu_label_sign_in: () => LocalizedString
	/**
	 * send me a reset link
	 */
	password_action_submit: () => LocalizedString
	/**
	 * reinitialize password
	 */
	password_reset_action_new_password: () => LocalizedString
	/**
	 * Please fill in your email
	 */
	password_reset_error_missing_parameters: () => LocalizedString
	/**
	 * We are sorry, no account has been found with the email {email} !
	 */
	password_reset_error_no_account_found: (arg: { email: string }) => LocalizedString
	/**
	 * Your password reset request is too old. Please issue a new request.
	 */
	password_reset_error_too_old: () => LocalizedString
	/**
	 * Your password reset request has been lost. Please try again or contact us.
	 */
	password_reset_error_wrong_code: () => LocalizedString
	/**
	 * New password
	 */
	password_reset_label_new_password: () => LocalizedString
	/**
	 * Reset your SKit password, configure your web app, see the power of a thoughtful-code approach
	 */
	password_reset_seo_description: () => LocalizedString
	/**
	 * SKit - reset password
	 */
	password_reset_seo_title: () => LocalizedString
	/**
	 * All good, you may reset your password
	 */
	password_reset_success: () => LocalizedString
	/**
	 * Lost your password?
	 */
	password_reset_title: () => LocalizedString
	/**
	 * Reset your password
	 */
	password_reset_title_password: () => LocalizedString
	/**
	 * Configure your SKit account, configure your web app, see the power of a thoughtful-code approach
	 */
	settings_seo_description: () => LocalizedString
	/**
	 * SKit - user config
	 */
	settings_seo_title: () => LocalizedString
	/**
	 * Sign in
	 */
	sign_in_action_submit: () => LocalizedString
	/**
	 * An account with the email {email} already exists!
	 */
	sign_in_error_email_exists: (arg: { email: string }) => LocalizedString
	/**
	 * The email and password should be provided
	 */
	sign_in_error_missing_data: () => LocalizedString
	/**
	 * Sign in to SKit, configure your web app, see the power of a thoughtful-code approach
	 */
	sign_in_seo_description: () => LocalizedString
	/**
	 * SKit - sign in
	 */
	sign_in_seo_title: () => LocalizedString
	/**
	 * Sign in
	 */
	sign_in_title: () => LocalizedString
	/**
	 * All good, your account has already been validated
	 */
	user_validation_error_already_validated: () => LocalizedString
	/**
	 * All good, your account just got validated :)
	 */
	user_validation_success: () => LocalizedString
}

export type Formatters = {}
